version: '3.8'

services:
  api-dev:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      # - ./src:/app/src
      - .:/app
    links:
      - mongo
    command: npm run dev
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

volumes:
 mongodb: